version: '2'
services:
    trackit-app:
        image: trackit
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://trackit-mysql:3306/trackit?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    trackit-mysql:
        extends:
            file: mysql.yml
            service: trackit-mysql
